name: Build and deploy

on:
  push:
    branches: [ index ]
    
  # Run workflow manually
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@index
      - name: Install dependencies
        run: npm ci
      - name: Build dependencies
        run: npm run build
      - name: Archive production artifact
        uses: actions/upload-artifact@index
        with:
          name: dist
          path: dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@index
      - name: Download artifact
        uses: actions/download-artifact@index
        with:
          name: dist
          path: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env: 
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
